### ISSUE TITLE
Theme kit fails to watch on Windows 7 64bit

### ISSUE THREAD

**Issue by jared83** [Shopify/themekit#158]
I followed installation instructions. The themekit even updated to the newest version, but whenever I run `theme watch` it gives me this error:

```
PS C:\Users\Administrator.MEY\Desktop\Website> theme watch
DEPRECATION WARNING: 'access_token' (in conf.yml) will soon be deprecated. Use 'password' instead, with the same Password value obtained from https://<your-subdomain>.myshopify.com/admin/apps/private/<a
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x4be2d3]

goroutine 1 [running]:
github.com/Shopify/themekit.findDirectoriesToWatch.func1(0xc0820a85a0, 0x10c, 0x0, 0x0, 0x361cb0, 0xc0822d33e0, 0x0, 0x0)
        /Users/chris/go/src/github.com/Shopify/themekit/file_watcher.go:79 +0x53
path/filepath.walk(0xc0821e0200, 0xfb, 0x1a4700, 0xc0824611a0, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:370 +0x41c
path/filepath.walk(0xc082324e10, 0xee, 0x1a4700, 0xc082460de0, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082324780, 0xe1, 0x1a4700, 0xc082460c00, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082450b60, 0xd4, 0x1a4700, 0xc082460840, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082200000, 0xb7, 0x1a4700, 0xc082359a40, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0822bc580, 0xaa, 0x1a4700, 0xc082358d80, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821be3c0, 0x93, 0x1a4700, 0xc0821ba7e0, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0821f0510, 0x86, 0x1a4700, 0xc0821ba480, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082489b00, 0x7d, 0x1a4700, 0xc082345080, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0822e2000, 0x70, 0x1a4700, 0xc082344d20, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc0823aea10, 0x64, 0x1a4700, 0xc0823c74a0, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082331440, 0x57, 0x1a4700, 0xc0823314a0, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc08219ecc0, 0x51, 0x1a4700, 0xc08219ed20, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082184cd0, 0x44, 0x1a4700, 0xc0821865a0, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc08213e900, 0x37, 0x1a4700, 0xc08217f740, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.walk(0xc082061050, 0x2a, 0x1a4700, 0xc082013560, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x503
path/filepath.Walk(0xc082061050, 0x2a, 0xc08205edb8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:396 +0xe8
github.com/Shopify/themekit.findDirectoriesToWatch(0xc082061050, 0x2a, 0x1, 0xc08205ef08, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/chris/go/src/github.com/Shopify/themekit/file_watcher.go:88 +0x1a2
github.com/Shopify/themekit.NewFileWatcher(0xc082061050, 0x2a, 0x1, 0xc082009640, 0x3, 0x4, 0xa6ba80, 0x0, 0x0, 0xa6ba80, ...)
        /Users/chris/go/src/github.com/Shopify/themekit/file_watcher.go:51 +0xc4
github.com/Shopify/themekit/commands.constructFileWatcher(0xc082061050, 0x2a, 0x0, 0xc0820093c0, 0x20, 0xc082009420, 0x20, 0xc0820094a0, 0x19, 0xc082060f90, ...)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/watch.go:104 +0xfb
github.com/Shopify/themekit/commands.watchForChangesAndIssueWork(0x0, 0xc0820093c0, 0x20, 0xc082009420, 0x20, 0xc0820094a0, 0x19, 0xc082060f90, 0x27, 0x0, ...)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/watch.go:68 +0x1cc
github.com/Shopify/themekit/commands.Watch(0x0, 0xc0820093c0, 0x20, 0xc082009420, 0x20, 0xc0820094a0, 0x19, 0xc082060f90, 0x27, 0x0, ...)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/watch.go:49 +0x458
github.com/Shopify/themekit/commands.WatchCommand(0xc082060bd0, 0xc082060ba0)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/watch.go:28 +0x171
main.main()
        /Users/chris/go/src/github.com/Shopify/themekit/cmd/theme/main.go:125 +0x2c4

goroutine 5 [chan receive]:
github.com/Shopify/themekit.SetErrorReporter.func2()
        /Users/chris/go/src/github.com/Shopify/themekit/error_reporter.go:50 +0x4c
created by github.com/Shopify/themekit.SetErrorReporter
        /Users/chris/go/src/github.com/Shopify/themekit/error_reporter.go:56 +0x6f

goroutine 6 [select]:
net/http.(*Transport).getConn(0xc0820501b0, 0xc0820e0000, 0x0, 0x8db320, 0x5, 0xc0820de030, 0x25, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:554 +0x66a
net/http.(*Transport).RoundTrip(0xc0820501b0, 0xc0820e0000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:228 +0x4b3
net/http.send(0xc0820e0000, 0x1a4440, 0xc0820501b0, 0xc0820da040, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:220 +0x533
net/http.(*Client).send(0xa476a0, 0xc0820e0000, 0x3e, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:143 +0x161
net/http.(*Client).doFollowingRedirects(0xa476a0, 0xc0820e0000, 0x902e18, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:380 +0xbc7
net/http.(*Client).Get(0xa476a0, 0x8db320, 0x3e, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:306 +0xb1
net/http.Get(0x8db320, 0x3e, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:281 +0x4c
github.com/Shopify/themekit/commands.downloadReleaseForPlatform(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/update.go:57 +0x7b
github.com/Shopify/themekit/commands.IsNewReleaseAvailable(0x0)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/update.go:35 +0x23
main.checkForUpdate()
        /Users/chris/go/src/github.com/Shopify/themekit/cmd/theme/main.go:106 +0x2b
created by main.main
        /Users/chris/go/src/github.com/Shopify/themekit/cmd/theme/main.go:118 +0x536

goroutine 7 [chan send]:
github.com/Shopify/themekit/commands.logEvent.func1(0xc0820123c0, 0x1a4868, 0xc08200c690)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/common.go:153 +0x52
created by github.com/Shopify/themekit/commands.logEvent
        /Users/chris/go/src/github.com/Shopify/themekit/commands/common.go:154 +0x50

goroutine 17 [chan receive]:
net/http.(*Transport).dialConn(0xc0820501b0, 0x0, 0x8db320, 0x5, 0xc0820de030, 0x25, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:668 +0x7ff
net/http.(*Transport).getConn.func4(0xc0820501b0, 0x0, 0x8db320, 0x5, 0xc0820de030, 0x25, 0xc0820ec000)
        /usr/local/go/src/net/http/transport.go:549 +0x6d
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:551 +0x26c

goroutine 19 [runnable, locked to thread]:
syscall.getprocaddress(0x7fefd500000, 0xc0821e2090, 0xc0821e2090, 0x0)
        /usr/local/go/src/runtime/syscall_windows.go:113 +0x66
syscall.(*DLL).FindProc(0xc0821ae840, 0x8b0ca0, 0x20, 0x8, 0x0, 0x0)
        /usr/local/go/src/syscall/dll_windows.go:74 +0xb0
syscall.(*LazyProc).Find(0xc082005170, 0x0, 0x0)
        /usr/local/go/src/syscall/dll_windows.go:243 +0x125
syscall.(*LazyProc).mustFind(0xc082005170)
        /usr/local/go/src/syscall/dll_windows.go:257 +0x28
syscall.(*LazyProc).Addr(0xc082005170, 0x408e55)
        /usr/local/go/src/syscall/dll_windows.go:266 +0x28
syscall.CertVerifyCertificateChainPolicy(0x4, 0x2b22ea0, 0xc08227ef18, 0xc08227ef28, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_windows.go:1180 +0x42
crypto/x509.checkChainSSLServerPolicy(0xc082024d80, 0x2b22ea0, 0xc08227f350, 0x0, 0x0)
        /usr/local/go/src/crypto/x509/root_windows.go:117 +0x13e
crypto/x509.(*Certificate).systemVerify(0xc082024d80, 0xc08227f350, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/x509/root_windows.go:212 +0x4dd
crypto/x509.(*Certificate).Verify(0xc082024d80, 0xc0820de030, 0x21, 0xc0822d2810, 0x0, 0xeceb9a241, 0x1d0eb948, 0xa47720, 0x0, 0x0, ...)
        /usr/local/go/src/crypto/x509/verify.go:215 +0x86
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc08227fe38, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/handshake_client.go:271 +0x6de
crypto/tls.(*Conn).clientHandshake(0xc0822d6000, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/handshake_client.go:206 +0x1655
crypto/tls.(*Conn).Handshake(0xc0822d6000, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:974 +0xf3
net/http.(*Transport).dialConn.func3(0xc0822d6000, 0xc0820062c0, 0xc08225c000)
        /usr/local/go/src/net/http/transport.go:662 +0x28
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:667 +0x7c3
PS C:\Users\Administrator.MEY\Desktop\Website>
```

I have a machine running Win 8.1 64bit, and had no problems with the themekit.

**Comment by jared83** [comment]
Sorry, never mind. It turned out that I was running the `theme watch` command in a wrong directory (the root directory of my project, where I kept all my build scripts). My shopify folders/theme was one level deeper in a 'shopify' directory about which I completely forgot. Silly me. However, it would be nice if the theme kit could give a friendly error message, say "no shopify theme found in this directory" if it cannot detect a shopify theme. The above stack trace is so confusing it got me searching for a solution to this trivial (human) error in all the wrong places, and waste a whole lot of time.
cheers

**Comment by ilikeorangutans** [comment]
Yah, It's true; that stacktrace is not exactly useful.

**Comment by ilikeorangutans** [comment]
@jared83 Just trying to reproduce (on Mac OS X) this error and I'm not sure I fully understand how you got this error. So you started `theme watch` in a directory _above_ the actual directory? For example, `~/parent` vs `~/parent/shopify`? Is there a `config.yml` in that directory? When I try to run `theme watch` in a directory outside of that, I get `2016/05/13 17:29:07 configuration error: open /Users/jakob/tmp/config.yml: no such file or directory`.

**Comment by tanema** [comment]
Closing because stale but also the newest version of the cmd also handles this more gracefully.
