### ISSUE TITLE
Unexpected Host Unkown error during replace or upload

### ISSUE THREAD

**Issue by jonathanmoore** [Shopify/themekit#190]
In the process of switching from the old theme gem to themekit I am running into an issue where running `theme replace` or `theme upload` will error on a random file Update or Remove during the process.  At times the error will happen after working through 4-5 files and other times it will occur after 30+ files.

So far I have not been able to successfully complete `theme replace` or `theme upload` with one of our premium themes or even a stripped down simple theme.  I have even tested it with multiple developer stores.  Additionally, I have been in touch with Lisa Villeneuve on the Shopify theme support team to get an extra set of eyes on the error.

Each time the files will begin to process and then I will see errors similar to the following happen with random files:
``` bash
[999]Could not perform Update to templates/gift_card.liquid at Host Unknown
        Put https://style-hatch-sandbox.myshopify.com/admin/assets.json: x509: certificate has expired or is not yet valid
[999]Could not perform Remove to assets/homepage_featured_box_4_image.jpg at Host Unknown
        dial tcp 23.227.38.70:443: i/o timeout
```

I'm currently using Theme Kit v0.4.2, but I also tested this same issue with 0.4.1 and 0.4.0.  Also, I'm seeing the same error reporting issue as #187 where the user "chris" is appearing.

### Screenshots
![image](https://cloud.githubusercontent.com/assets/454095/18563546/db796898-7b3c-11e6-9196-45b4a7d01760.png)

![image](https://cloud.githubusercontent.com/assets/454095/18563660/5cbbd2e2-7b3d-11e6-94d0-e84ee0c0e4be.png)

![image](https://cloud.githubusercontent.com/assets/454095/18563674/7014da46-7b3d-11e6-86d7-2cf02dc96cd2.png)

### Full Example Error

```
± ~/dev/stylehatch/shopify/sections/district/dist (master ✗) $ theme replace
Successfully performed Update operation for file snippets/icon-american_express.liquid to style-hatch-sandbox.myshopify.com
Successfully performed Update operation for file snippets/icon-discover.liquid to style-hatch-sandbox.myshopify.com
Successfully performed Update operation for file templates/page.liquid to style-hatch-sandbox.myshopify.com
Successfully performed Update operation for file snippets/icon-snapchat.liquid to style-hatch-sandbox.myshopify.com
[999]Could not perform Remove to assets/icons.svg at Host Unknown
        dial tcp 23.227.38.69:443: i/o timeout
unexpected fault address 0x1d3cea6671cb
fatal error: fault
[signal 0xb code=0x1 addr=0x1d3cea6671cb pc=0x1d3cea6671cb]

goroutine 84 [running]:
runtime.throw(0x4bff80, 0x5)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82043a880 sp=0xc82043a868
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc82043a8d0 sp=0xc82043a880
net/http.(*Transport).dial(0xc8200c6000, 0x4c1f18, 0x3, 0xc8203fe5a0, 0x25, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:662 +0x96 fp=0xc82043a960 sp=0xc82043a8d0
net/http.(*Transport).dialConn(0xc8200c6000, 0x0, 0xc8202a61c0, 0x5, 0xc8203fe5a0, 0x25, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:765 +0x1e3d fp=0xc82043af00 sp=0xc82043a960
net/http.(*Transport).getConn.func4(0xc8200c6000, 0x0, 0xc8202a61c0, 0x5, 0xc8203fe5a0, 0x25, 0xc820018420)
        /usr/local/go/src/net/http/transport.go:709 +0x66 fp=0xc82043af78 sp=0xc82043af00
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82043af80 sp=0xc82043af78
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:711 +0x262

goroutine 1 [chan receive]:
main.main()
        /Users/chris/go/src/github.com/Shopify/themekit/cmd/theme/main.go:140 +0x354

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/Shopify/themekit.SetErrorReporter.func2()
        /Users/chris/go/src/github.com/Shopify/themekit/error_reporter.go:58 +0x45
created by github.com/Shopify/themekit.SetErrorReporter
        /Users/chris/go/src/github.com/Shopify/themekit/error_reporter.go:64 +0x68

goroutine 7 [select]:
net/http.(*Transport).getConn(0xc8200c6000, 0xc8202421c0, 0x0, 0xc8202a61c0, 0x5, 0xc8203fe5a0, 0x25, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:714 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200c6000, 0xc8202421c0, 0xc8200c6000, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:314 +0x7e9

net/http.send(0xc8202421c0, 0xa14528, 0xc8200c6000, 0x0, 0xc800000000, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82000f500, 0xc8202421c0, 0x0, 0x0, 0x0, 0x1b, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).Do(0xc82000f500, 0xc8202421c0, 0xc8200bea20, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:193 +0x2b1
github.com/Shopify/themekit.ThemeClient.request(0x0, 0x0, 0xc8200bea20, 0x20, 0xc820011208, 0x4, 0xc82000f440, 0x21, 0xc82000f4d0, 0x2f
, ...)
        /Users/chris/go/src/github.com/Shopify/themekit/theme_client.go:322 +0x3d0
github.com/Shopify/themekit.ThemeClient.Perform(0x0, 0x0, 0xc8200bea20, 0x20, 0xc820011208, 0x4, 0xc82000f440, 0x21, 0xc82000f4d0, 0x2f
, ...)
        /Users/chris/go/src/github.com/Shopify/themekit/theme_client.go:266 +0x1ec
github.com/Shopify/themekit.ThemeClient.Process.func1(0xc8200189c0, 0xc82002e0b8, 0xc820116000, 0xc82002e0b0)
        /Users/chris/go/src/github.com/Shopify/themekit/theme_client.go:243 +0xad
created by github.com/Shopify/themekit.ThemeClient.Process
        /Users/chris/go/src/github.com/Shopify/themekit/theme_client.go:250 +0x143

goroutine 8 [chan receive]:
github.com/Shopify/themekit/commands.mergeEvents.func1(0xc82002e0c0, 0x1, 0x1, 0xc820018360)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/common.go:24 +0xab
created by github.com/Shopify/themekit/commands.mergeEvents
        /Users/chris/go/src/github.com/Shopify/themekit/commands/common.go:30 +0x53

goroutine 22 [select]:
main.main.func1(0xc82032e300, 0xc820018a20)
        /Users/chris/go/src/github.com/Shopify/themekit/cmd/theme/main.go:126 +0x2ac
created by main.main
        /Users/chris/go/src/github.com/Shopify/themekit/cmd/theme/main.go:139 +0x32e

goroutine 19 [IO wait]:
net.runtime_pollWait(0xa91000, 0x72, 0xc820157000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82014e060, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82014e060, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82014e000, 0xc820157000, 0x1000, 0x1000, 0x0, 0xa10050, 0xc820010058)
        /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820146018, 0xc820157000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820130480, 0xa91110, 0xc820146018, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820154000, 0x584317, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820154000, 0xc820179000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xa50ab8, 0xc820154000, 0xc820138068, 0xc820179000, 0x1000, 0x1000, 0xb9c3, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1690 +0x67
net/http.(*noteEOFReader).Read(0xc82041c3c0, 0xc820179000, 0x1000, 0x1000, 0xc820143d0d, 0x0, 0x0)
        <autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8201327e0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201327e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820138000)
        /usr/local/go/src/net/http/transport.go:1076 +0x177
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:860 +0x10a6

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc820138000)
        /usr/local/go/src/net/http/transport.go:1280 +0x472
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:861 +0x10cb

goroutine 46 [chan send]:
github.com/Shopify/themekit/commands.fullReplace.func2(0xc8203aa000, 0xc8200189c0)
        /Users/chris/go/src/github.com/Shopify/themekit/commands/replace.go:49 +0xcd
created by github.com/Shopify/themekit/commands.fullReplace
        /Users/chris/go/src/github.com/Shopify/themekit/commands/replace.go:52 +0x100
```

**Comment by jonathanmoore** [comment]
To help debug the issue a bit further, I set up `mitmproxy` to try to figure out what is triggering the error during the replace or upload process.  However, while `proxy: http://localhost:8080` is set in the config.yml file and `mitmproxy` is running, I'm finally able to fully perform `theme upload` or `theme replace`.

My guess is that the SSL certificate validation is the cause of the errors, since using the proxy URL disables them.

```
Proxy URL detected from Configuration: http://localhost:8080
SSL Certificate Validation will be disabled!
```

This should still be an open issue since I shouldn't have to rely on disabling SSL certificate validation.  It also feels like 1 out of every 10 times I'm seeing the process hang on a random file similar to #172

**Comment by jonathanmoore** [comment]
After quite a bit of testing it seems like `0.4.3` fixed all the issues I was running into.
https://github.com/Shopify/themekit/tree/0.4.3

My guess is that 8434c32497dc41905959e6635b4531a253523c32 took care of it.

**Comment by tanema** [comment]
Thanks for testing it out @jonathanmoore though that commit is not in the 0.4.3 release. However the newest build was done with a newer version of Go. We have seen many improvements from just this so I am glad to hear that it has cleared up your issues as well. Keep us updated.
