### ISSUE TITLE
theme watch - "Runtime Error: invalid memory address or nil pointer dereference" after many updates in v0.5.1

### ISSUE THREAD

**Issue by brettchalupa** [Shopify/themekit#246]
I upgraded to v0.5.1 yesterday, and when saving files to be updated by `theme watch`, a `panic: runtime error: invalid memory address or nil pointer dereference` error is thrown.

The seems to be occurring after saving the file ~12 times, which is then followed by `theme watch` crashing.

Here is the full error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6a018]

goroutine 97 [running]:
panic(0x36dd20, 0xc4200120e0)
        /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/Shopify/themekit/kit.(*httpClient).AssetAction(0xc4200f9200, 0x2, 0xc4203b8050, 0xe, 0xc4204d4000, 0xeafe, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/http_client.go:112 +0x1e8
github.com/Shopify/themekit/kit.ThemeClient.Perform(0xc4203dd520, 0x20, 0xc4203d5958, 0x4, 0xc4203309c0, 0x27, 0xc420014084, 0x2e, 0xc4202be080, 0x3, ...)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/theme_client.go:156 +0x311
github.com/Shopify/themekit/cmd.handleWatchEvent(0xc4203dd520, 0x20, 0xc4203d5958, 0x4, 0xc4203309c0, 0x27, 0xc420014084, 0x2e, 0xc4202be080, 0x3, ...)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/cmd/watch.go:67 +0x364
github.com/Shopify/themekit/kit.handleEvent(0xc4203f23c0, 0xc420315940, 0x3d, 0xc400000002)
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/file_watcher.go:140 +0x209
created by github.com/Shopify/themekit/kit.callbackEvents
        /Users/timanema/workspace/go/src/github.com/Shopify/themekit/kit/file_watcher.go:94 +0x14e
```

Additional details:

- Go v1.7.1 (darwin/amd64)
- macOS Sierra - v10.12 (16A323)
- File is a JS file in the `assets` dir

Let me know if there is any additional info I can provide, and I'll share anything else I come across.

**Comment by tanema** [comment]
Hey @brettchalupa I just created a PR for a fix for this however this would only happen if the request fails for some reason. The PR will catch that error and log it however there shouldn't really be an error at that step anyways. Are you saving the same file 12 times? Is it all in a row?

**Comment by brettchalupa** [comment]
@tanema Yup, it is the same file I am saving consecutively. I'm not saving it a bunch intentionally in rapid intervals though, just saving it as I made changes to the file (maybe twice a minute or so). I have only been working with that one JS file, so if I notice it happen with another file during development I'll share details about that too.

**Comment by tanema** [comment]
I reopened this because I added error handling for this and this should log a valid error now, but I imagine it will be a request error.

**Comment by tanema** [comment]
I have released version v0.5.2 that will handle that panic, please try it out.

**Comment by brettchalupa** [comment]
@tanema sounds good, will do. Thank you! I'll upgrade today and report anything new there.
