### ISSUE TITLE
Python errors on new install. Connection timed out

### ISSUE THREAD

**Issue by patrickbolle** [Shopify/themekit#353]
Hi folks.
Brand new system running Debian Testing with zsh instead of bash.
Just ran the curl command and it takes a minute or so, then lines up all the errors below:

```
curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python

Downloading themekit from github.com//Shopify/themekit/releases/download/v0.6.9/linux-amd64.zip

Traceback (most recent call last):
  File "<stdin>", line 126, in <module>
  File "<stdin>", line 76, in install
  File "<stdin>", line 89, in __download
  File "<stdin>", line 19, in get
  File "<stdin>", line 13, in get
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 110] Connection timed out
```

Any ideas here?

Thanks!
`

**Comment by patrickbolle** [comment]
Ahh... this could be because of this? https://status.shopify.com/

**Comment by jjui** [comment]
Could be! I get 
```
	Status: 500 Internal Server Error
	Errors: Internal Server Error
```
Went here to see if any issues related, so probably...

**Comment by tanema** [comment]
Hey All, AWS is experiencing some issues which is where the install binaries are stored. In a pinch you can download the binaries from the releases on github and put it in your `/usr/local/bin`

**Comment by tanema** [comment]
The AWS outtage is cleared up now! Cheers.
