### ISSUE TITLE
Install fails: newest release doesn't have all zip files available

### ISSUE THREAD

**Issue by frehner** [Shopify/themekit#380]
This means themekit installs fail

**Comment by frehner** [comment]
Using
`RUN curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | python `
to install for reference.

**Comment by frehner** [comment]
```Traceback (most recent call last):
  File "<stdin>", line 126, in <module>
Downloading themekit from github.com//Shopify/themekit/releases/download/v0.6.11/linux-amd64.zip
Installing themekit to /usr/local/bin
  File "<stdin>", line 78, in install
  File "<stdin>", line 99, in __unzip
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

**Comment by tanema** [comment]
oh sorry, did the release without my coffee this morning. Once second I will fix that

**Comment by tanema** [comment]
Fixed

**Comment by frehner** [comment]
Confirmed. Thanks for the quick response.
