### ISSUE TITLE
Installer doesn't work on NixOS

### ISSUE THREAD

**Issue by bsima** [Shopify/themekit#633]
Two elements to this problem:

1. shebang should be the POSIX-compliant `#!/usr/bin/env python` instead of `#!/usr/bin/python`
2. If NixOS is detected, you could just execute the correct `nix-env -i` command, or give the user an alternate install instructions, instead of manually downloading the binary into the bin path.

**Comment by bsima** [comment]
This is the python traceback, btw

```
[nix-shell:~/work]$ python install-shopify-themekit.py 
Fetching release data
Downloading version v1.0.0 of Shopify Themekit
Validated binary checksum
Traceback (most recent call last):
  File "install-shopify-themekit.py", line 62, in <module>
    Installer()
  File "install-shopify-themekit.py", line 30, in __init__
    self.__download()
  File "install-shopify-themekit.py", line 56, in __download
    os.makedirs(self.install_path)
  File "/nix/store/9kigl3bk51mfn0484y72w3zlm7d8ws76-python-2.7.16/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/nix/store/9kigl3bk51mfn0484y72w3zlm7d8ws76-python-2.7.16/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local'
```

**Comment by bsima** [comment]
Here is a nix expression that seems to work:

```nix
with import <nixpkgs> {};

# docs: https://nixos.org/nixpkgs/manual/#sec-language-go

let
  version = "1.0.0";
in
buildGoModule rec {
  name = "themekit-${version}";
  src = fetchFromGitHub {
    owner = "Shopify";
    repo = "themekit";
    rev = "v${version}";
    sha256 = "1xbgc30fd1vz3fqaai869h0jyy9ifhb6q5qxcx5zmk7f3d1wj72l";
  };
  modSha256 = "1dls2gjcyvd0ligk8ra6lk2ppsisf57b6xzgws7av4zds173qqsp";
}
```

Save this as, say, `themekit.nix`, then `nix-build themekit.nix` and `nix-env -i ./result`.

**Comment by tanema** [comment]
Hey @bsima thanks for opening the issue and giving me so much information!

You seem to have a bit more context on this than I, so I will defer to you but are you suggesting that if I use `#!/usr/bin/env python` it will more likely succeed and not give you permissions errors when the script runs?

I would prefer to not create a specialized installation method for this platform and keep most of our installation paths limited, although briefly reading up on NixOS it seems like it allows a per-project user space so it seems unlikely. Is there some sort of repository that I could host an installable package on? I will need to do some reading on this to be able to fully understand what is required.

**Comment by bsima** [comment]
Nix doesn't allow you to just copy stuff to `/usr/bin` - all the normal paths like that are write-protected. Instead, Nix installs stuff to `/nix/store/` and then brings it into your `$PATH` via symlinks. It uses a hashing function (I think it uses content + platform + version) to allow multiple packages with the same name to exist in `/nix/store`. It's a bit more complex than that, but that's the gist. Afaik it's the best way to cryptographically guarantee reproducible builds.

>  Is there some sort of repository that I could host an installable package on?

You could submit it to [nixpkgs](https://github.com/nixos/nixpkgs). The snippet I posted above is basically complete, take a look at [this similar go program](https://github.com/NixOS/nixpkgs/blob/52dae14f0c763dd48572058f0f0906166da14c31/pkgs/applications/misc/todoist/default.nix). Once it's in nixpkgs, anyone with NixOS or the nix package manager could just `nix-env -i themekit` and it would install, they could also get themekit in a temporary shell with `nix-shell -p themekit`.

If you decide to put this on nixpkgs, lemme know (tag me in the PR or email ben@bsima.me) and I can help review.

> You seem to have a bit more context on this than I, so I will defer to you but are you suggesting that if I use `#!/usr/bin/env python` it will more likely succeed and not give you permissions errors when the script runs?

No, this is just the POSIX-compliant way to do it. I believe `#!/usr/bin/python` will fail on some BSDs too.

Lemme know if I can help further :)

**Comment by tanema** [comment]
Okay I will fix the script, and open a PR to get themekit in to the pkgs repo when I release 1.0.1. Thanks for your help!
