### ISSUE TITLE
Ubuntu SSL: CERTIFICATE_VERIFY_FAILED | Installer error

### ISSUE THREAD

**Issue by ittisafur** [Shopify/themekit#748]
**Describe the bug**
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**To Reproduce**
1. run command 'curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python'

Running this I got 
`
Fetching release data
Traceback (most recent call last):
  File "<stdin>", line 62, in <module>
  File "<stdin>", line 28, in __init__
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 215, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 445, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1303, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
`

**Expected behavior**
Complete the installation.

**Environment (please complete the following information):**
 - OS : Ubuntu 18.04

**Additional context**
I checked my openssl version it returns 1.1.1g. How can I solve this ?

**Comment by ittisafur** [comment]
I was able to resolve it by the manual installation
