### ISSUE TITLE
`install.py` is unable to download files (`latest.json` and then `theme`)

### ISSUE THREAD

**Issue by huguesbr** [Shopify/themekit#798]
**Describe the bug**
`install.py` doesn't seem to be able to download required files.. due to some s3 permissions?

**To Reproduce**
1. `curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python`
```
Fetching release data
Traceback (most recent call last):
  File "./install.py", line 63, in <module>
    Installer()
  File "./install.py", line 28, in __init__
    self.release = json.loads(urllib.urlopen(Installer.LATEST_RELEASE_URL).read().decode("utf-8"))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Here it the inspected request results
```
curl -H 'User-Agent: Python-urllib/1.17' -H 'Accept: */*' 'https://shopify-themekit.s3.amazonaws.com/releases/latest.json'

<Error>
	<Code>AccessDenied</Code>
	<Message>Access Denied</Message>
	<RequestId>B5449324A2363657</RequestId>
	<HostId>u8zqAcZwO7/BBRC1Os9B5+S3sAaqZsmRMXizJeiy0tNv/TV3pwuZro160C+b+aTk50vkSgCNIgs=</HostId>
</Error>
```

same for the `theme`

```
curl -H 'User-Agent: Python-urllib/1.17' -H 'Accept: */*' 'https://shopify-themekit.s3.amazonaws.com/v1.1.1/darwin-amd64/theme'

<Error>
	<Code>NoSuchBucket</Code>
	<Message>The specified bucket does not exist</Message>
	<BucketName>v1.1.1</BucketName>
	<RequestId>A3CFB8A1F72CA4C1</RequestId>
	<HostId>sk2k0nn4nuNykKgVcD+3wNtRevlDUSwzlP1E47VoDAiVXBk6hl2Zh/XnbvEbKr2JMdkJeDLAVKw=</HostId>
</Error>
```

**Expected behavior**
install theme

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS
- Themekit version [e.g. v0.7.5]: latest
 - Editor [e.g. atom, sublime]: 
 - Ignore:

**Additional context**
I've been able to make it works by manually downloading the files (`latest.json` and `theme`) and updating the python script

```
#!/usr/bin/env python
'''
    File name: install
    Author: Tim Anema
    Date created: Sep 29, 2016
    Date last modified: Sep 14 2018
    Python Version: 2.7
    Description: Install script for themekit. It will download a release and make it executable
'''
import os, urllib, json, sys, hashlib

class Installer(object):
    LATEST_RELEASE_URL = "https://shopify-themekit.s3.amazonaws.com/releases/latest.json"
    ARCH_MAPPING = {
        "darwin x86_64": "darwin-amd64",
        "darwin i386": "darwin-386",
        "linux x86_64": "linux-amd64",
        "linux i386": "linux-386",
        "freebsd x86_64": "freebsd-amd64",
        "freebsd i386": "freebsd-386"
    }

    def __init__(self, path="/usr/local/bin"):
        self.install_path = os.path.expanduser(path)
        self.bin_path = "%s/theme" % self.install_path
        self.arch = self.__getArch()
        print("Fetching release data")
        # data = urllib.urlopen(Installer.LATEST_RELEASE_URL).read().decode("utf-8")
        # ⚠️ reading local file
        f = open('latest.json', 'r')
        data = f.read().decode("utf-8")
        self.release = json.loads(data)
        print("Downloading version %s of Shopify Themekit" % self.release['version'])
        self.__download()
        print("Theme Kit has been installed at %s" % self.bin_path)
        print('To verify themekit is working simply type "theme"')

    def __getArch(self):
        pipe = os.popen("echo \"$(uname) $(uname -m)\"")
        arch_name = pipe.readline().strip().lower()
        pipe.close()
        if arch_name not in Installer.ARCH_MAPPING:
            print("Cannot find binary to match your architecture [%s]" % arch_name)
            sys.exit("Please open an issue at https://github.com/Shopify/themekit/issues")
        return Installer.ARCH_MAPPING[arch_name]

    def __findReleasePlatform(self):
        for index, platform in enumerate(self.release['platforms']):
            if platform['name'] == self.arch:
                return platform

    def __download(self):
        platform = self.__findReleasePlatform()
        # data = urllib.urlopen(platform['url']).read()
        # ⚠️ reading local file
        f = open('theme', 'r')
        data = f.read()
        if hashlib.md5(data).hexdigest() != platform['digest']:
            sys.exit("Downloaded binary did not match checksum.")
        else:
            print("Validated binary checksum")
        if not os.path.exists(self.install_path):
            os.makedirs(self.install_path)
        with open(self.bin_path, "wb") as themefile:
            themefile.write(data)
        os.chmod(self.bin_path, 0o755)

if sys.version_info[0] < 3:
    Installer()
else:
    sys.exit("Python 2 is required for this script.")
```

**Comment by andyw8** [comment]
Hi @huguesbr, that is strange. So you're able to access https://shopify-themekit.s3.amazonaws.com/releases/latest.json in your browser but not with curl?

I confirmed that it's working for me:

```
$ curl -H 'User-Agent: Python-urllib/1.17' -H 'Accept: */*' 'https://shopify-themekit.s3.amazonaws.com/releases/latest.json'

{"version":"v1.1.1","platforms":[{"name":"linux-386","url":"https://shopify-themekit.s3.amazonaws.com/v1.1.1/linux-386/theme","digest":"a06df36646c6708204d4af2f69eeca27"},{"name":"linux-amd64","url":"https://shopify-themekit.s3.amazonaws.com/v1.1.1/linux-amd64/theme","digest":"7a4a280d8dc57cbd3a50e44c9058fbbc"},{"name":"freebsd-386","url":"https://shopify-themekit.s3.amazonaws.com/v1.1.1/freebsd-386/theme","digest":"295e07e03afc55af09108e8ee591134f"},{"name":"freebsd-amd64","url":"https://shopify-themekit.s3.amazonaws.com/v1.1.1/freebsd-amd64/theme","digest":"eca3be174bba29e816f9599fdb5f9cb9"},{"name":"windows-386","url":"https://shopify-themekit.s3.amazonaws.com/v1.1.1/windows-386/theme.exe","digest":"cee0ece1e248ce7e9d4f340045dcdbb3"},{"name":"windows-amd64","url":"https://shopify-themekit.s3.amazonaws.com/v1.1.1/windows-amd64/theme.exe","digest":"3a1fb85c06922a842d6cec841c302e3a"},{"name":"darwin-amd64","url":"https://shopify-themekit.s3.amazonaws.com/v1.1.1/darwin-amd64/theme","digest":"be650ea27d25b47eabb6fadc55f22620"},{"name":"darwin-386","url":"https://shopify-themekit.s3.amazonaws.com/v1.1.1/darwin-386/theme","digest":"bc3ff94a08a9f5f95edb851e4ef0e5c6"}]}
```

Could you try run `nslookup shopify-themekit.s3.amazonaws.com` and share the output?

**Comment by huguesbr** [comment]
oh my! so sorry, I had Charles Proxy in the loop and I guess that's what made it go crazy, all good, thx!

**Comment by andyw8** [comment]
@huguesbr good to hear.
