### ISSUE TITLE
Apple M1 build crashes when trying to build dependency of themekit

### ISSUE THREAD

**Issue by aamistad** [Shopify/themekit#851]
Was running into this issue trying to setup my dev environment on a new mac mini. Not sure if its something on my end or something that needs to be updated.

```[4/4] 🔨  Building fresh packages...
[6/15] ⠠ gifsicle
[9/15] ⠠ pngquant-bin
[7/15] ⠠ mozjpeg
[4/15] ⠠ @shopify/themekit
error /Users/andrewamistad/Sites/dry-farm-wines/node_modules/@shopify/themekit: Command failed.
Exit code: 1
Command: node ./lib/cli.js install
Arguments:
Directory: /Users/andrewamistad/Sites/dry-farm-wines/node_modules/@shopify/themekit
Output:
-/Users/andrewamistad/Sites/dry-farm-wines/node_modules/@shopify/themekit/lib/install.js:46
        throw runErr;
        ^

Error: The `/Users/andrewamistad/Sites/dry-farm-wines/node_modules/@shopify/themekit/bin/theme` binary doesn't seem to work correctly
    at BinWrapper.<anonymous> (/Users/andrewamistad/Sites/dry-farm-wines/node_modules/bin-wrapper/index.js:156:7)
    at ChildProcess.<anonymous> (/Users/andrewamistad/Sites/dry-farm-wines/node_modules/bin-check/index.js:26:4)```

**Comment by andyw8** [comment]
@aamistad Do you have your Terminal set to 'Open in Rosetta'?

**Comment by aamistad** [comment]
@andyw8 yes terminal is set to open using Rosetta. I've also attempted reinstalling themekit, brew and reinstalled command line tools

**Comment by tanema** [comment]
Please open this on the https://github.com/Shopify/node-themekit repo as it looks like an installation issue with the node library. We have seen success with others using themekit directly on M1
