### ISSUE TITLE
using an old config file and not accepting updates throws panic error

### ISSUE THREAD

**Issue by jtgrenz** [Shopify/themekit#87]
If you have a folder that already has a ruby theme gem config file, running a command will prompt that the config file is out of date. If you say no, then there is a panic runtime error

[![alt](https://screenshot.click/15-55-j6bkn-44ygu.jpg)](https://screenshot.click/15-55-j6bkn-44ygu.jpg)

Raw 

```
➜  Simple git:(master) ✗ theme replace
Looks like your configuration file is out of date. Upgrading to default environment 'development'
Compare changes to configuration:
Before:
 ---
:api_key: < API KEY >
:password: < API PASSWORD >
:store: < Store Name >
:theme_id:
:whitelist_files:
- directoryToUpload/
- importantFile.txt
:ignore_files:
        #- config/settings.html
- config.yml

After:
 development:
  access_token: ""
  store: ""
  bucket_size: 40
  refill_rate: 2
  concurrency: 2

Does this look correct? (y/n)
n
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xe1e72]

goroutine 10 [running]:
net/http.(*Client).doFollowingRedirects(0x0, 0xc20801ec30, 0x480c10, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:304 +0x62
net/http.(*Client).Do(0x0, 0xc20801ec30, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:174 +0xa4
github.com/Shopify/themekit.ThemeClient.query(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:230 +0x28b
github.com/Shopify/themekit.func·020()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:95 +0x5e
created by github.com/Shopify/themekit.ThemeClient.AssetList
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:112 +0x18b

goroutine 1 [chan receive]:
main.main()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/cmd/theme/main.go:127 +0x3aa

goroutine 5 [runnable]:
github.com/Shopify/themekit.func·002()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:50 +0x52
created by github.com/Shopify/themekit.SetErrorReporter
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:56 +0x69

goroutine 7 [chan send]:
github.com/Shopify/themekit.func·003()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:62 +0x55
created by github.com/Shopify/themekit.func·004
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:63 +0x73

goroutine 8 [chan receive]:
github.com/Shopify/themekit.func·025()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:189 +0x9a
created by github.com/Shopify/themekit.ThemeClient.Process
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:198 +0x1d8

goroutine 9 [chan receive]:
github.com/Shopify/themekit/commands.func·002()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/common.go:142 +0xbf
created by github.com/Shopify/themekit/commands.mergeEvents
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/common.go:148 +0xd8

goroutine 11 [runnable]:
github.com/Shopify/themekit/commands.drainErrors(0xc20803f2c0)
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/common.go:127
created by github.com/Shopify/themekit/commands.Replace
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/replace.go:28 +0x20c

goroutine 12 [runnable]:
github.com/Shopify/themekit/commands.removeAndUpload(0xc20803f260, 0xc20803f140)
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/replace.go:53
created by github.com/Shopify/themekit/commands.Replace
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/replace.go:29 +0x236

goroutine 13 [runnable]:
main.func·001()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/cmd/theme/main.go:110
created by main.main
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/cmd/theme/main.go:126 +0x382
```

@csaunders

**Comment by csaunders** [comment]
The YAML parser I'm using isn't compatible with the way Ruby wants it to be formatted. A work around for this is to simply fix up your configuration by removing the prefixed `:` and it should then be able to migrate your configuration over.

I'm not sure if it's worth submitting a patch to the YAML library for this. I am pretty sure that's not part of the spec. Could it be that Ruby takes keys that `:look_like_this:` and translates them into symbols?

**Comment by jtgrenz** [comment]
Seems to be a ruby feature for sure. Running it through http://www.yamllint.com/

```
---
:api_key: < API KEY >
:password: < API PASSWORD>
:store: jtgrenz.myshopify.com
:theme_id: 12403338
:whitelist_files:
- directoryToUpload/
- importantFile.txt
:ignore_files:
        #- config/settings.html
- config.yml
```
Becomes :
```
--- 
? !ruby/symbol api_key
: < API KEY >
? !ruby/symbol ignore_files
: 
  - config.yml
? !ruby/symbol password
: < API PASSWORD>
? !ruby/symbol store
: jtgrenz.myshopify.com
? !ruby/symbol theme_id
: 12403338
? !ruby/symbol whitelist_files
: 
  - directoryToUpload/
  - importantFile.txt
```

but passes as valid YAML. The old theme gem has this style setup as its demos https://github.com/Shopify/shopify_theme#the-configyml-file So I'm not sure how backwards compatible we want to be. If themekit is designed to try and convert an existing configuration to the new model, it should fail in most cases if it can't handle the conversion from ruby symbols. I reckon most people using the gem would have copy and pasted the sample.

**Comment by csaunders** [comment]
As a result of https://github.com/Shopify/themekit/pull/95 this will no longer throw the error. The only thing missing is to perhaps prompt the user to update their configuration by hand.

If that is sufficient, please close the issue.
