### ISSUE TITLE
invalid CLI Args should fail gracefully

### ISSUE THREAD

**Issue by jtgrenz** [Shopify/themekit#89]
Right now entering invalid arguments causes the tool to throw a panic when there should ideally be some error handling 

[![alt](https://screenshot.click/15-46-ptv25-6jnwm.jpg)](https://screenshot.click/15-46-ptv25-6jnwm.jpg)

is a little scary looking. A better message would be something like
```
Unknown argument "ddfgdg". 
<output usage banner>
```

**Comment by csaunders** [comment]
What version of the tool are you using (`theme version`). On v0.2.7 I see some 406 errors pop up, but the application still runs correctly.

If `config.yml` is missing I get a gross error, but it's different than this one.

**Comment by jtgrenz** [comment]
```
➜  ~  theme version
Theme Kit v0.2.7
```

Its actually giving me the 406 errors now too. Using the wrong config.yml gives me issue https://github.com/Shopify/themekit/issues/87 

Running the command sans config.yml file gives me a different error (probably the one you got too)

```
➜  Simple git:(master) ✗ ls
assets         config         config.yml_gem config.yml_kit layout         locales        snippets       templates
➜  Simple git:(master) ✗ theme replace kdhfkdfdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xe1e72]

goroutine 10 [running]:
net/http.(*Client).doFollowingRedirects(0x0, 0xc208034c30, 0x480c10, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:304 +0x62
net/http.(*Client).Do(0x0, 0xc208034c30, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/client.go:174 +0xa4
github.com/Shopify/themekit.ThemeClient.query(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:230 +0x28b
github.com/Shopify/themekit.func·020()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:95 +0x5e
created by github.com/Shopify/themekit.ThemeClient.AssetList
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:112 +0x18b

goroutine 1 [chan receive]:
main.main()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/cmd/theme/main.go:127 +0x3aa

goroutine 5 [runnable]:
github.com/Shopify/themekit.func·002()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:50 +0x52
created by github.com/Shopify/themekit.SetErrorReporter
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:56 +0x69

goroutine 7 [chan send]:
github.com/Shopify/themekit.func·003()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:62 +0x55
created by github.com/Shopify/themekit.func·004
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:63 +0x73

goroutine 8 [chan receive]:
github.com/Shopify/themekit.func·025()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:189 +0x9a
created by github.com/Shopify/themekit.ThemeClient.Process
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/theme_client.go:198 +0x1d8

goroutine 9 [chan receive]:
github.com/Shopify/themekit/commands.func·002()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/common.go:142 +0xbf
created by github.com/Shopify/themekit/commands.mergeEvents
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/common.go:148 +0xd8

goroutine 11 [runnable]:
github.com/Shopify/themekit/commands.drainErrors(0xc20803e4e0)
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/common.go:127
created by github.com/Shopify/themekit/commands.Replace
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/replace.go:28 +0x20c

goroutine 12 [runnable]:
github.com/Shopify/themekit/commands.removeAndUpload(0xc20803e480, 0xc20803e360)
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/replace.go:53
created by github.com/Shopify/themekit/commands.Replace
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/commands/replace.go:29 +0x236

goroutine 13 [runnable]:
main.func·001()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/cmd/theme/main.go:110
created by main.main
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/cmd/theme/main.go:126 +0x382
```

I'm not longer able to replicate the original issue, but a missing config file should fail gracefully too. I wish i knew what happened to cause that slice error originally though.

**Comment by csaunders** [comment]
Thanks! 

![](http://media2.giphy.com/media/PjRo6vL5m9212/giphy.gif)

**Comment by jtgrenz** [comment]
When running `theme` without arguments, it throws an error on v0.3

```
➜  Simple git:(master) ✗ theme
panic: runtime error: index out of range

goroutine 1 [running]:
main.SetupAndParseArgs(0xc20800a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/cmd/theme/main.go:295 +0x11d
main.main()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/cmd/theme/main.go:120 +0xba

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
github.com/Shopify/themekit.func·002()
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:48
created by github.com/Shopify/themekit.SetErrorReporter
	/Users/csaunders/development/golang/src/github.com/Shopify/themekit/error_reporter.go:56 +0x69
```

Invalid arguments work great though
