### ISSUE TITLE
Themekit Proxy causes Seg Violation

### ISSUE THREAD

**Issue by claridgicus** [Shopify/themekit#894]
Use of the proxy is causing this seg violation

Its a pretty standard setup it just contains the theme url password and a proxy

This is running inside ubuntu 18.04 which normally has no issue with regular theme commands - but with a proxied request it goes 💥 

```
[development] Proxy URL detected from Configuration [insert a valid url here] SSL Certificate Validation will be disabled!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x858312]

goroutine 1 [running]:
github.com/Shopify/themekit/src/httpify.(*HTTPClient).doWithRetry(0xc0002282c0, 0xc000034100, 0x0, 0x0, 0x1, 0xc0000a4590, 0x0)
        /Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:130 +0x102
github.com/Shopify/themekit/src/httpify.(*HTTPClient).do(0xc0002282c0, 0x973595, 0x3, 0x9759c4, 0xa, 0x0, 0x0, 0x0, 0x0, 0xc0005363a0, ...)
        /Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:105 +0x5d1
github.com/Shopify/themekit/src/httpify.(*HTTPClient).Get(0xc0002282c0, 0x9759c4, 0xa, 0x0, 0x21, 0xdd0ae0, 0xd)
        /Users/andyw8/src/github.com/Shopify/themekit/src/httpify/client.go:70 +0x6d
github.com/Shopify/themekit/src/shopify.Client.GetShop(0xc00047e480, 0xc, 0xc00012a390, 0x21, 0xdd0ae0, 0xd, 0xd, 0xc0000a4520, 0x1, 0x1, ...)
        /Users/andyw8/src/github.com/Shopify/themekit/src/shopify/theme_client.go:128 +0x88
github.com/Shopify/themekit/src/cmdutil.createCtx(0x9986a8, 0xc00022c750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/andyw8/src/github.com/Shopify/themekit/src/cmdutil/util.go:96 +0xec
github.com/Shopify/themekit/src/cmdutil.generateContexts(0x9986a8, 0xc000460340, 0xc00012a1e0, 0x2b, 0x0, 0x0, 0xc0000cfd80, 0x1, 0x1, 0x0, ...)
        /Users/andyw8/src/github.com/Shopify/themekit/src/cmdutil/util.go:218 +0x495
github.com/Shopify/themekit/src/cmdutil.forEachClient(0x9986a8, 0xc00012a1e0, 0x2b, 0x0, 0x0, 0xc0000cfd80, 0x1, 0x1, 0x0, 0x0, ...)
        /Users/andyw8/src/github.com/Shopify/themekit/src/cmdutil/util.go:281 +0xed
github.com/Shopify/themekit/src/cmdutil.ForEachClient(...)
        /Users/andyw8/src/github.com/Shopify/themekit/src/cmdutil/util.go:276
github.com/Shopify/themekit/cmd.glob..func12(0xdca080, 0xc0000f3120, 0x0, 0x2, 0x0, 0x0)
        /Users/andyw8/src/github.com/Shopify/themekit/cmd/watch.go:36 +0xe0
github.com/spf13/cobra.(*Command).execute(0xdca080, 0xc0000f30c0, 0x2, 0x2, 0xdca080, 0xc0000f30c0)
        /Users/andyw8/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20180722215644-7c4570c3ebeb/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xdc9960, 0x13, 0x0, 0x0)
        /Users/andyw8/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20180722215644-7c4570c3ebeb/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/andyw8/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20180722215644-7c4570c3ebeb/command.go:800
main.main()
        /Users/andyw8/src/github.com/Shopify/themekit/cmd/theme/main.go:29 +0x61
```

**Comment by tanema** [comment]
What version of themekit?
